Add error check for if there is a version mismatch
Currently, if a user does not have a matching version of the SQL CLI to our version map, they get the following error:

astro flow deploy
Error: Malformed constraint:

This does not help much in determining why the deployment is failing.

This PR adds better context so that future CREs can better aide customers.